# Generated by Django 5.1.3 on 2024-11-30 17:21

import ckeditor_uploader.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='biography')),
                ('avatar', models.ImageField(default='defaults/default-userprofile-avatar.jpg', upload_to='avatars/', verbose_name='avatar')),
                ('display_personal_page', models.BooleanField(default=False, verbose_name='display personal page')),
                ('slug', models.SlugField(max_length=30)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'user profile',
                'verbose_name_plural': 'user profile',
                'default_permissions': ('change',),
            },
        ),
    ]
