services:
  # Backend server -------------------------------------------------------------
  django:
    build:
      context: .
      dockerfile: docker/django.Dockerfile
    environment:
      - SECRET_KEY=$SECRET_KEY
      - DJANGO_LOG_LEVEL=$DJANGO_LOG_LEVEL
      - TIME_ZONE=$TIME_ZONE
      - DISQUS_API_KEY=$DISQUS_API_KEY
      - DISQUS_WEBSITE_SHORTNAME=$DISQUS_WEBSITE_SHORTNAME
    volumes:
      - ./radioco/media/:/radioco/radioco/media/
    links:
      - postgres

  postgres:
    image: postgres:13.0
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    volumes:
      - database_data:/var/lib/postgresql/data

# Volumes ---------------------------------------------------------------------

volumes:
  database_data:
    name: database_data
