#!/bin/bash
# This deploy hook gets executed after dependencies are resolved and the
# build hook has been run but before the application has been started back
# up again.  This script gets executed directly, so it could be python, php,
# ruby, etc.

echo "Executing 'python $OPENSHIFT_REPO_DIRradioco/configs/openshift/manage.py migrate --noinput'"
python "$OPENSHIFT_REPO_DIR"radioco/configs/openshift/manage.py migrate --noinput

echo "Executing 'python $OPENSHIFT_REPO_DIRradioco/configs/openshift/manage.py collectstatic --noinput'"
python "$OPENSHIFT_REPO_DIR"radioco/configs/openshift/manage.py collectstatic --noinput
