# Generated by Django 5.1.3 on 2024-11-30 17:20

import django.db.models.deletion
import recurrence.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('programmes', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='name')),
                ('is_active', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'calendar',
                'verbose_name_plural': 'calendar',
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('L', 'live'), ('B', 'broadcast'), ('S', 'broadcast syndication')], max_length=1, verbose_name='type')),
                ('recurrences', recurrence.fields.RecurrenceField(help_text='Excluded dates will appear in this list as result of dragging and dropping.', verbose_name='recurrences')),
                ('start_dt', models.DateTimeField(verbose_name='start date')),
                ('effective_start_dt', models.DateTimeField(blank=True, help_text='This field is dynamically generated to improve performance', null=True, verbose_name='first effective start date')),
                ('effective_end_dt', models.DateTimeField(blank=True, help_text='This field is dynamically generated to improve performance', null=True, verbose_name='last effective end date')),
                ('calendar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedules.calendar', verbose_name='calendar')),
                ('from_collection', models.ForeignKey(blank=True, help_text='Parent schedule (only happens when it is changed from recurrence.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_schedules', to='schedules.schedule')),
                ('programme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programmes.programme', verbose_name='programme')),
                ('source', models.ForeignKey(blank=True, help_text='Main schedule when (if this is a broadcast).', null=True, on_delete=django.db.models.deletion.SET_NULL, to='schedules.schedule', verbose_name='source')),
            ],
            options={
                'verbose_name': 'schedule',
                'verbose_name_plural': 'schedules',
            },
        ),
        migrations.CreateModel(
            name='ExcludedDates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(db_index=True)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedules.schedule')),
            ],
        ),
    ]
