#!/usr/bin/env python

import os
import sys

sys.path.append(os.path.join(os.environ['OPENSHIFT_REPO_DIR']))

os.environ.setdefault("DJANGO_SETTINGS_MODULE", "radioco.configs.openshift.settings")

# from distutils.sysconfig import get_python_lib
# os.environ['PYTHON_EGG_CACHE'] = get_python_lib()

import django.core.wsgi
application = django.core.wsgi.get_wsgi_application()
