# Generated by Django 5.1.3 on 2024-11-30 17:21

import ckeditor_uploader.fields
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='title')),
                ('summary', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='summary')),
                ('issue_date', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='issue date')),
                ('season', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='season')),
                ('number_in_season', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='No. in season')),
            ],
            options={
                'verbose_name': 'episode',
                'verbose_name_plural': 'episodes',
                'permissions': (('see_all_episodes', 'Can see all episodes'),),
            },
        ),
        migrations.CreateModel(
            name='Programme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='name')),
                ('synopsis', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='synopsis')),
                ('photo', models.ImageField(default='defaults/default-programme-photo.jpg', upload_to='photos/', verbose_name='photo')),
                ('language', models.CharField(choices=[('es', 'Spanish'), ('en', 'English'), ('gl', 'Galician')], default='es', max_length=7, verbose_name='language')),
                ('current_season', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='current season')),
                ('category', models.CharField(blank=True, choices=[('Arts', 'Arts'), ('Business', 'Business'), ('Comedy', 'Comedy'), ('Education', 'Education'), ('Games & Hobbies', 'Games & Hobbies'), ('Government & Organizations', 'Government & Organizations'), ('Health', 'Health'), ('Kids & Family', 'Kids & Family'), ('Music', 'Music'), ('News & Politics', 'News & Politics'), ('Religion & Spirituality', 'Religion & Spirituality'), ('Science & Medicine', 'Science & Medicine'), ('Society & Culture', 'Society & Culture'), ('Sports & Recreation', 'Sports & Recreation'), ('Technology', 'Technology'), ('TV & Film', 'TV & Film')], max_length=50, null=True, verbose_name='category')),
                ('slug', models.SlugField(help_text="Please DON'T change this value. It's used to build URL's.", max_length=100, unique=True)),
                ('_runtime', models.PositiveIntegerField(help_text='In minutes.', validators=[django.core.validators.MinValueValidator(1)], verbose_name='runtime')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='start date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='end date')),
            ],
            options={
                'verbose_name': 'programme',
                'verbose_name_plural': 'programmes',
                'permissions': (('see_all_programmes', 'Can see all programmes'),),
            },
        ),
        migrations.CreateModel(
            name='Podcast',
            fields=[
                ('episode', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='podcast', serialize=False, to='programmes.episode')),
                ('url', models.CharField(max_length=2048)),
                ('mime_type', models.CharField(max_length=20)),
                ('length', models.PositiveIntegerField()),
                ('duration', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('podcast_file', models.FileField(blank=True, upload_to='podcasts/')),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, max_length=60, null=True, verbose_name='role')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('episode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programmes.episode', verbose_name='episode')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='person')),
            ],
            options={
                'verbose_name': 'contributor',
                'verbose_name_plural': 'contributors',
                'permissions': (('see_all_participants', 'Can see all participants'),),
                'unique_together': {('person', 'episode')},
            },
        ),
        migrations.AddField(
            model_name='episode',
            name='people',
            field=models.ManyToManyField(blank=True, through='programmes.Participant', to=settings.AUTH_USER_MODEL, verbose_name='people'),
        ),
        migrations.AddField(
            model_name='episode',
            name='programme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programmes.programme', verbose_name='programme'),
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, max_length=60, null=True, verbose_name='role')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('date_joined', models.DateField(auto_now_add=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='person')),
                ('programme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programmes.programme', verbose_name='programme')),
            ],
            options={
                'verbose_name': 'role',
                'verbose_name_plural': 'roles',
                'permissions': (('see_all_roles', 'Can see all roles'),),
                'unique_together': {('person', 'programme')},
            },
        ),
        migrations.AddField(
            model_name='programme',
            name='announcers',
            field=models.ManyToManyField(blank=True, through='programmes.Role', to=settings.AUTH_USER_MODEL, verbose_name='announcers'),
        ),
        migrations.AlterUniqueTogether(
            name='episode',
            unique_together={('season', 'number_in_season', 'programme')},
        ),
    ]
