# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-03-06 18:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programmes', '0011__v3_2__ensure_one_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='podcast',
            name='podcast_file',
            field=models.FileField(blank=True, upload_to='podcasts/'),
        ),
    ]
